# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86753552257222dbe170a1d2bdcdaaccb3e2ca119a7fd71d73a0f728fbfd6afcc457d75b336fa976bb98eb4701557be1458f4a91e519eaf0866b2f2b8ed78935

test:
  secret_key_base: 4e8bccec152d86bd6ce305306afa49c8a3c2abccaddac475cd650e81d82a5036a0da32faa4849e0024925077991416ee1d8a06e9f7e6468854981e6fc3ddd9cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
